#!/bin/bash

#
# Fetch build number from Git revision number.
#
GITREV=`git rev-list HEAD --count`

#
# Is the build tracked by Git?
#
if [ "x$GITREV" = "x" ]
then
    GITREV="Untracked"
fi

cat >kernel/vers.c <<EOF
/*
 * This file is automatically generated.
 * DO NOT EDIT!
 */

const int buildno = ${GITREV};
EOF
